name: face2face_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  # Paquetes principales actualizados y con el nombre CORRECTO
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  http: ^1.2.1
  geolocator: ^12.0.0
  
  google_maps_flutter: ^2.5.0

  file_picker: ^8.0.3
  socket_io_client: ^3.0.0

  # Paquetes de Firebase que ya añadimos (con versiones compatibles)
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.0

  # Iconos de Cupertino
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/boxing_bg.jpg